# Site settings
title: Carie Phon | Designer + Developer
email: hello@cariephon.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Carie Phon. I'm a designer and developer who loves taking complex ideas and translating them into simple yet sophisticated websites and applications that are charming, intuitive, and fun to use.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cariephon.com" # the base hostname & protocol for your site
twitter_username: cariephon
github_username:  gloomyTofu

gems:
  - jemoji
  
sass:
    style: :compressed
  
# Build settings
# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
markdown: rdiscount

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# How many articles do you wish to appear on the front page:
paginate: 3

